### ISSUE TITLE
Which python version should i use?

### ISSUE THREAD

**Issue by lucaoskaique** [Akascape/Datamosher-Pro#2]
I downloaded the python windows version for studies and what python version should i use?

**Comment by Akascape** [comment]
Python v3.9+ will work. But latest version (3.10) is recommended. You can download it from here: https://www.python.org/downloads/
After installing, just run that datamosher-pro.py file (simply open it), It will ask you to install some extra modules, click on "Yes" and let the modules be downloaded automatically (The process will appear in the terminal). 
Then the program will open and you can use it.
If you face any other issue then comment. 
BTW, The GUI is a little old fashioned but I am currently working on a new modern GUI which will be available soon! :)

**Comment by lucaoskaique** [comment]
Do you accept pull requests? i would like to get involve. I'm always down to learn new stuff and contribute with awesome projects

**Comment by Akascape** [comment]
For now, I want to develop this project personally only.
But for your studies,
I will first recommend you to research on some repositories/tools which are the base for this application. You can find those links in the conclusion part of the readme. Specially learning about FFglitch will be more exciting. Improving those scripts/tools means improving this repo. You can say that this application is a mixture of those scripts with lots of improvements so that a normal user can use it. If you are able to make any new effects from those original stuff then you can contribute here also. I will then try to implement that feature in my application for everyone.
I hope you understand :)

**Comment by lucaoskaique** [comment]
Sure friend, tks for the tips!!!! i'll look into it.
I work full time as software engineer and to soften the bunout i try to lean things intersecting programming && art.
