### ISSUE TITLE
tkinter module won't install

### ISSUE THREAD

**Issue by fartfartfarty** [Akascape/Datamosher-Pro#5]
The automatic setup on open says that all folders are available but not all modules are installed, all the other modules listed in the manual setup wiki are there except tkinter. Running the pip install command shows this error in cmd. 
`pip install tkinter
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter`
I also tried installing tk but nothing changed when I ran Setup.py.

**Comment by Akascape** [comment]
@fartfartfarty First of all please mention your OS.
Generally tkinter module is there by default so there is no need to install it separately. I think its not because of tkinter module.

Try running Datamosher-Pro.py file directly. If it shows any import error on the console then please report it here.
 
Otherwise you can do the third manual step and move forward.

Moreover the required modules in the automatic setup are these:

`required = {'imageio', 'imageio-ffmpeg', 'numpy', 'customtkinter', 'pillow', 'rangeslider', 'requests'}`

It will show that 'unavailable module' error message only if these are not installed at first.

Try checking all your modules with `pip -list` and make sure the required ones are properly installed.

**Comment by fartfartfarty** [comment]
I use Windows 10.

I'm not really sure what you mean by "run directly", but when I try to run Datamosher Pro.py by double clicking the file it opens command prompt for a split second and then instantly closes. If I try opening it using cmd this is what happens:

`C:\Users\gHost>"Downloads\Datamosher-Pro_python-version (1)\Datamosher Pro\Datamosher Pro.py"
Traceback (most recent call last):
  File "C:\Users\gHost\Downloads\Datamosher-Pro_python-version (1)\Datamosher Pro\Datamosher Pro.py", line 8, in <module>
    import customtkinter
ModuleNotFoundError: No module named 'customtkinter'`

`C:\Users\gHost>pip install customtkinter
Requirement already satisfied: customtkinter in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (4.5.10)
Requirement already satisfied: darkdetect in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from customtkinter) (0.7.1)`

`C:\Users\gHost>"Downloads\Datamosher-Pro_python-version (1)\Datamosher Pro\Datamosher Pro.py"
Traceback (most recent call last):
  File "C:\Users\gHost\Downloads\Datamosher-Pro_python-version (1)\Datamosher Pro\Datamosher Pro.py", line 8, in <module>
    import customtkinter
ModuleNotFoundError: No module named 'customtkinter'`

I ran the pip list command and all modules you listed are there. I'm unsure on how to check if they are properly installed but I ran pip download, install, and check on all of these and nothing seemed to be wrong. Not sure if this is helpful but this is after running Setup.py
`All folders available!
Some modules are not installed
 do you want to download and install them? (Y/N): y
Installing modules...
Requirement already satisfied: requests in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (2.28.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (2022.6.15)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (1.26.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (3.3)
Requirement already satisfied: imageio-ffmpeg in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (0.4.7)
Requirement already satisfied: numpy in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.23.2)
Requirement already satisfied: rangeslider in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (2021.7.4)
Requirement already satisfied: imageio in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (2.21.1)
Requirement already satisfied: numpy in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from imageio) (1.23.2)
Requirement already satisfied: pillow>=8.3.2 in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from imageio) (9.2.0)
Requirement already satisfied: pillow in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (9.2.0)
Requirement already satisfied: customtkinter in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (4.5.10)
Requirement already satisfied: darkdetect in c:\users\ghost\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from customtkinter) (0.7.1)
Checking FFglitch:
Running ffgac...
ffgac version ffglitch-0.9.3 Copyright (c) 2000-2021 the FFmpeg developers
  FFglitch Copyright (c) 2017-2021 Ramiro Polla
built with gcc 6.3.0 (GCC) 20170516
configuration: --disable-doc --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=win64 --enable-gpl --enable-static --disable-shared --extra-ldflags=-static
Running ffedit...
ffedit version ffglitch-0.9.3 Copyright (c) 2000-2021 the FFmpeg developers
  FFglitch Copyright (c) 2017-2021 Ramiro Polla
built with gcc 6.3.0 (GCC) 20170516
configuration: --disable-doc --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=win64 --enable-gpl --enable-static --disable-shared --extra-ldflags=-static
Done...
Setup Complete!`

**Comment by Akascape** [comment]
Everthing seems to be right, you have all modules installed but python is not able to import them.

I think it's because of PATH (environment variables) associated with python.

Two solutions I can reccomend:
Try running the Datamosher-Pro.py file in IDLE mode. 
Just right click on the py file and click on `Edit with IDLE`>`Edit with IDLE 3.10`. It will then open the file contents, just press `F5` on your keyboard to run the file in that mode.

Second solution:
Open your `python3.10 setup.exe` and click on `Modify`. Click Next and check the box written as `Add Python to environment variable` and just click Install.

Close the setup and then try running the Datamosher.py file again.

These are actually some basic things in python.

**Comment by Akascape** [comment]
Everthing seems to be right, you have all modules installed but python is not able to import them.

it's because of PATH (environment variables) associated with python.

Two solutions I can reccomend:
Try running the Datamosher-Pro.py file in IDLE mode. 
Just right click on the py file and click on `Edit with IDLE`>`Edit with IDLE 3.10`. It will then open the file contents, just press `F5` on your keyboard to run the file in that mode.

Second solution:
Open your `python setup.exe` and click on `Modify`. Click Next and check the box written as `Add Python to environment variables` and just click Install. Put the new version paths in the top of environment variables (if you are using windows)

![Screenshot 2022-08-31 105136](https://user-images.githubusercontent.com/89206401/187598502-2547fdaa-9a85-4076-ae3a-0ce6bbce936f.png)


Close the setup and then try running the Datamosher.py file again.

These are actually some basic things in python you have to do. Please let me know if its working.

**Comment by fartfartfarty** [comment]
The second solution worked! After checking the Add Python to environment variables I ran Setup.py again and it downloaded the modules again and then the Datamosher Pro.py ran after I double clicked it. Thanks!

**Comment by vicky02000** [comment]
Hello! 
Its my very first time using python on mac os, so I’m sorry If I dont use the right words. I installed pip, setuptools, all the required modules (tkinter, pillow etc…) . I maneged to complete setup.py but when I try to open datamosher, it says that I need to impor pkg. resources and that the api is deprecated. What does this mean and how can I fix this? Thank you so much :)

**Comment by Akascape** [comment]
@vicky02000 Install packaging `pip install packaging`.
If you are getting `DeprecationWarning: pkg_resources is deprecated as an API` while opening setup.py then ignore it. Directly run datamosher-pro.py file

**Comment by vicky02000** [comment]
Thank You so so much!
