### ISSUE TITLE
Can't Find the ffmpeg

### ISSUE THREAD

**Issue by FarmehrF** [Akascape/Datamosher-Pro#6]
Hi, I've successfully run the python program but when creating the file I get this error
> /bin/sh: Datamosher-Pro/Python Version/ffmpeg: No such file or directory

I've installed ffmpeg using homebrew and it's clearly installed right now.
After running "brew list | grep ffmpeg" I get:
>  ffmpeg

Also running "pip3 list | grep ffmpeg"  results in:

> ffmpeg             1.4
imageio-ffmpeg     0.4.7

Do I need to create some kind of folder and put some ffmpeg files where 'Data Mosher.py' is?

**Comment by Akascape** [comment]
@FarmehrF I guess there is some problem getting the imageio-ffmpeg in mac.
Can you please try this version (1.81): https://github.com/Akascape/Datamosher-Pro/releases/tag/Datamosher_Prov1.8%2C1

Let me know if this one works properly. 

I have actually changed the ffmpeg path method in version 1.9 which maybe causing this issue in mac only.

**Comment by Akascape** [comment]
Hi @FarmehrF ,
You just need to install imageio-ffmpeg which have a ffmpeg binary attached. So, there is no need to install ffmpeg separately.
I hope you are using the latest version of datamosher-pro (v1.9)

Can you let me know the output of this python code in your system so that I can know if imageio-ffmpeg is properly installed:
```python
import imageio_ffmpeg
print(imageio_ffmpeg.get_ffmpeg_exe())
```
If you are getting some similar path like this, then your ffmpeg is installed properly:
`Python/lib/site-packages/imageio_ffmpeg/binaries/ffmpeg-osx-v4.2.2`

If it's giving a different path, then try the second method:

**Second method**
Edit the datamosher-pro.py file in any text editor application and replace this line with a new code.

Remove the line 61:
```python
ffmpeg = resource(imageio_ffmpeg.get_ffmpeg_exe())
```
And paste these 3 new lines there:
```python
ffdir = os.path.dirname(imageio_ffmpeg.__file__).replace(os.sep, '/')+"/binaries/"
fileff = ''.join([idx for idx in os.listdir(ffdir) if idx[0].lower()=='f'.lower()])
ffmpeg = resource(ffdir+fileff)
```
Then try the modes like bloom or classic.
If these works, then I will give an update.

**Comment by FarmehrF** [comment]
The output of first method is just "ffmpeg" without any paths.
As for the second method, the program won't open and results in this error:

    FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/lib/python3.10/site-packages/imageio_ffmpeg/binaries/'

**Comment by Akascape** [comment]
@FarmehrF Ok, so it's the problem with your imageio-ffmpeg then. Actually the ffmpeg binary is not present in your imageio folder.
Try to reinstall imageio-ffmpeg.
There should be a ffmpeg file in this folder: `/opt/homebrew/lib/python3.10/site-packages/imageio_ffmpeg/binaries/`
Recheck if it's available there.

If reinstalling is not helping, then just replace that ffmpeg line to `ffmpeg = "ffmpeg"`
Or you can also add the ffmpeg file in the same datamosher-pro folder.

**Comment by FarmehrF** [comment]
@Akascape It worked!! I just copied the folder. There has to be some sort of problem between Mac and pip installing imageio_ffmpeg package.

**Comment by Akascape** [comment]
@FarmehrF 
Enjoy experimenting with videos :)
